# Logging configuration

logging:
  version: 1
  formatters:
    tradeETL:
      format: "tradeETL Transformer - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: tradeETL
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]